db.session_status.remove();
db.session_status.insert({label: 'Approuvé', version: '01', deleted: 'false'});
db.session_status.insert({label: 'Brouillon', version: '01', deleted: 'false'});
db.sponsor_level.remove();
db.sponsor_level.insert({label: 'Titanium', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Platine', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Or', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Argent', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Community', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Education', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Média', version: '01', deleted: 'false'});
db.category.remove();
db.category.insert({label: 'Android', version: '01', deleted: 'false'});
db.category.insert({label: 'HTML5', version: '01', deleted: 'false'});
db.category.insert({label: 'Java', version: '01', deleted: 'false'});
db.category.insert({label: 'Entreprise', version: '01', deleted: 'false'});
db.category.insert({label: 'Web Design', version: '01', deleted: 'false'});
db.category.insert({label: 'Community', version: '01', deleted: 'false'});
db.title.remove();
db.title.insert({label: 'M.', version: '01', deleted: 'false'});
db.title.insert({label: 'Mme', version: '01', deleted: 'false'});
db.title.insert({label: 'Mlle', version: '01', deleted: 'false'});