db.session_status.remove();
db.session_status.insert({label: 'Approuvé', version: '01', deleted: 'false'});
db.session_status.insert({label: 'Brouillon', version: '01', deleted: 'false'});
db.sponsor_level.remove();
db.sponsor_level.insert({label: 'Titanium', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Platine', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Or', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Argent', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Community', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Education', version: '01', deleted: 'false'});
db.sponsor_level.insert({label: 'Média', version: '01', deleted: 'false'});
db.category.remove();
db.category.insert({label: 'Android', version: '01', deleted: 'false'});
db.category.insert({label: 'Web', version: '01', deleted: 'false'});
db.category.insert({label: 'Java', version: '01', deleted: 'false'});
db.category.insert({label: 'Entreprise', version: '01', deleted: 'false'});
db.category.insert({label: 'Web Design', version: '01', deleted: 'false'});
db.category.insert({label: 'Community', version: '01', deleted: 'false'});
db.title.remove();
db.title.insert({label: 'M.', version: '01', deleted: 'false'});
db.title.insert({label: 'Mme', version: '01', deleted: 'false'});
db.title.insert({label: 'Mlle', version: '01', deleted: 'false'});
db.country.remove();
db.country.insert({cid: 'Afghanistan' , name: 'Afghanistan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Albania' , name: 'Albania', version: '01', deleted: 'false'});
db.country.insert({cid: 'Algeria' , name: 'Algeria', version: '01', deleted: 'false'});
db.country.insert({cid: 'Andorra' , name: 'Andorra', version: '01', deleted: 'false'});
db.country.insert({cid: 'Angola' , name: 'Angola', version: '01', deleted: 'false'});
db.country.insert({cid: 'Antigua and Barbuda' , name: 'Antigua and Barbuda', version: '01', deleted: 'false'});
db.country.insert({cid: 'Argentina' , name: 'Argentina', version: '01', deleted: 'false'});
db.country.insert({cid: 'Armenia' , name: 'Armenia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Australia' , name: 'Australia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Austria' , name: 'Austria', version: '01', deleted: 'false'});
db.country.insert({cid: 'Azerbaijan' , name: 'Azerbaijan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bahamas' , name: 'Bahamas', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bahrain' , name: 'Bahrain', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bangladesh' , name: 'Bangladesh', version: '01', deleted: 'false'});
db.country.insert({cid: 'Barbados' , name: 'Barbados', version: '01', deleted: 'false'});
db.country.insert({cid: 'Belarus' , name: 'Belarus', version: '01', deleted: 'false'});
db.country.insert({cid: 'Belgium' , name: 'Belgium', version: '01', deleted: 'false'});
db.country.insert({cid: 'Belize' , name: 'Belize', version: '01', deleted: 'false'});
db.country.insert({cid: 'Benin' , name: 'Benin', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bhutan' , name: 'Bhutan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bolivia' , name: 'Bolivia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bosnia and Herzegovina' , name: 'Bosnia and Herzegovina', version: '01', deleted: 'false'});
db.country.insert({cid: 'Botswana' , name: 'Botswana', version: '01', deleted: 'false'});
db.country.insert({cid: 'Brazil' , name: 'Brazil', version: '01', deleted: 'false'});
db.country.insert({cid: 'Brunei' , name: 'Brunei', version: '01', deleted: 'false'});
db.country.insert({cid: 'Bulgaria' , name: 'Bulgaria', version: '01', deleted: 'false'});
db.country.insert({cid: 'Burkina Faso' , name: 'Burkina Faso', version: '01', deleted: 'false'});
db.country.insert({cid: 'Burma' , name: 'Burma', version: '01', deleted: 'false'});
db.country.insert({cid: 'Burundi' , name: 'Burundi', version: '01', deleted: 'false'});
db.country.insert({cid: 'Cambodia' , name: 'Cambodia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Cameroon' , name: 'Cameroon', version: '01', deleted: 'false'});
db.country.insert({cid: 'Canada' , name: 'Canada', version: '01', deleted: 'false'});
db.country.insert({cid: 'Cape Verde' , name: 'Cape Verde', version: '01', deleted: 'false'});
db.country.insert({cid: 'Central African Republic' , name: 'Central African Republic', version: '01', deleted: 'false'});
db.country.insert({cid: 'Chad' , name: 'Chad', version: '01', deleted: 'false'});
db.country.insert({cid: 'Chile' , name: 'Chile', version: '01', deleted: 'false'});
db.country.insert({cid: 'China' , name: 'China', version: '01', deleted: 'false'});
db.country.insert({cid: 'Colombia' , name: 'Colombia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Comoros' , name: 'Comoros', version: '01', deleted: 'false'});
db.country.insert({cid: 'Democratic Republic of the Congo' , name: 'Democratic Republic of the Congo', version: '01', deleted: 'false'});
db.country.insert({cid: 'Republic of the Congo' , name: 'Republic of the Congo', version: '01', deleted: 'false'});
db.country.insert({cid: 'Costa Rica' , name: 'Costa Rica', version: '01', deleted: 'false'});
db.country.insert({cid: 'Croatia' , name: 'Croatia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Cuba' , name: 'Cuba', version: '01', deleted: 'false'});
db.country.insert({cid: 'Cyprus' , name: 'Cyprus', version: '01', deleted: 'false'});
db.country.insert({cid: 'Czech Republic' , name: 'Czech Republic', version: '01', deleted: 'false'});
db.country.insert({cid: 'Denmark' , name: 'Denmark', version: '01', deleted: 'false'});
db.country.insert({cid: 'Djibouti' , name: 'Djibouti', version: '01', deleted: 'false'});
db.country.insert({cid: 'Dominica' , name: 'Dominica', version: '01', deleted: 'false'});
db.country.insert({cid: 'Dominican Republic' , name: 'Dominican Republic', version: '01', deleted: 'false'});
db.country.insert({cid: 'East Timor' , name: 'East Timor', version: '01', deleted: 'false'});
db.country.insert({cid: 'Ecuador' , name: 'Ecuador', version: '01', deleted: 'false'});
db.country.insert({cid: 'Egypt' , name: 'Egypt', version: '01', deleted: 'false'});
db.country.insert({cid: 'El Salvador' , name: 'El Salvador', version: '01', deleted: 'false'});
db.country.insert({cid: 'Equatorial Guinea' , name: 'Equatorial Guinea', version: '01', deleted: 'false'});
db.country.insert({cid: 'Eritrea' , name: 'Eritrea', version: '01', deleted: 'false'});
db.country.insert({cid: 'Estonia' , name: 'Estonia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Ethiopia' , name: 'Ethiopia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Fiji' , name: 'Fiji', version: '01', deleted: 'false'});
db.country.insert({cid: 'Finland' , name: 'Finland', version: '01', deleted: 'false'});
db.country.insert({cid: 'France' , name: 'France', version: '01', deleted: 'false'});
db.country.insert({cid: 'Gabon' , name: 'Gabon', version: '01', deleted: 'false'});
db.country.insert({cid: 'Gambia, The' , name: 'Gambia, The', version: '01', deleted: 'false'});
db.country.insert({cid: 'Georgia' , name: 'Georgia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Germany' , name: 'Germany', version: '01', deleted: 'false'});
db.country.insert({cid: 'Ghana' , name: 'Ghana', version: '01', deleted: 'false'});
db.country.insert({cid: 'Greece' , name: 'Greece', version: '01', deleted: 'false'});
db.country.insert({cid: 'Grenada' , name: 'Grenada', version: '01', deleted: 'false'});
db.country.insert({cid: 'Guatemala' , name: 'Guatemala', version: '01', deleted: 'false'});
db.country.insert({cid: 'Guinea' , name: 'Guinea', version: '01', deleted: 'false'});
db.country.insert({cid: 'Guinea-Bissau' , name: 'Guinea-Bissau', version: '01', deleted: 'false'});
db.country.insert({cid: 'Guyana' , name: 'Guyana', version: '01', deleted: 'false'});
db.country.insert({cid: 'Haiti' , name: 'Haiti', version: '01', deleted: 'false'});
db.country.insert({cid: 'Honduras' , name: 'Honduras', version: '01', deleted: 'false'});
db.country.insert({cid: 'Hungary' , name: 'Hungary', version: '01', deleted: 'false'});
db.country.insert({cid: 'Iceland' , name: 'Iceland', version: '01', deleted: 'false'});
db.country.insert({cid: 'India' , name: 'India', version: '01', deleted: 'false'});
db.country.insert({cid: 'Indonesia' , name: 'Indonesia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Iran' , name: 'Iran', version: '01', deleted: 'false'});
db.country.insert({cid: 'Iraq' , name: 'Iraq', version: '01', deleted: 'false'});
db.country.insert({cid: 'Republic of Ireland' , name: 'Republic of Ireland', version: '01', deleted: 'false'});
db.country.insert({cid: 'Israel' , name: 'Israel', version: '01', deleted: 'false'});
db.country.insert({cid: 'Italy' , name: 'Italy', version: '01', deleted: 'false'});
db.country.insert({cid: 'Ivory Coast' , name: 'Ivory Coast', version: '01', deleted: 'false'});
db.country.insert({cid: 'Jamaica' , name: 'Jamaica', version: '01', deleted: 'false'});
db.country.insert({cid: 'Japan' , name: 'Japan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Jordan' , name: 'Jordan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kazakhstan' , name: 'Kazakhstan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kenya' , name: 'Kenya', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kiribati' , name: 'Kiribati', version: '01', deleted: 'false'});
db.country.insert({cid: 'North Korea' , name: 'North Korea', version: '01', deleted: 'false'});
db.country.insert({cid: 'South Korea ' , name: 'South Korea', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kuwait' , name: 'Kuwait', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kyrgyzstan' , name: 'Kyrgyzstan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Laos' , name: 'Laos', version: '01', deleted: 'false'});
db.country.insert({cid: 'Latvia' , name: 'Latvia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Lebanon' , name: 'Lebanon', version: '01', deleted: 'false'});
db.country.insert({cid: 'Lesotho' , name: 'Lesotho', version: '01', deleted: 'false'});
db.country.insert({cid: 'Liberia' , name: 'Liberia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Libya' , name: 'Libya', version: '01', deleted: 'false'});
db.country.insert({cid: 'Liechtenstein' , name: 'Liechtenstein', version: '01', deleted: 'false'});
db.country.insert({cid: 'Lithuania' , name: 'Lithuania', version: '01', deleted: 'false'});
db.country.insert({cid: 'Luxembourg' , name: 'Luxembourg', version: '01', deleted: 'false'});
db.country.insert({cid: 'Republic of Macedonia ' , name: 'Republic of Macedonia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Madagascar' , name: 'Madagascar', version: '01', deleted: 'false'});
db.country.insert({cid: 'Malawi' , name: 'Malawi', version: '01', deleted: 'false'});
db.country.insert({cid: 'Malaysia' , name: 'Malaysia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Maldives' , name: 'Maldives', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mali' , name: 'Mali', version: '01', deleted: 'false'});
db.country.insert({cid: 'Malta' , name: 'Malta', version: '01', deleted: 'false'});
db.country.insert({cid: 'Marshall Islands' , name: 'Marshall Islands', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mauritania' , name: 'Mauritania', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mauritius' , name: 'Mauritius', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mexico' , name: 'Mexico', version: '01', deleted: 'false'});
db.country.insert({cid: 'Federated States of Micronesia' , name: 'Federated States of Micronesia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Moldova' , name: 'Moldova', version: '01', deleted: 'false'});
db.country.insert({cid: 'Monaco' , name: 'Monaco', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mongolia' , name: 'Mongolia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Montenegro' , name: 'Montenegro', version: '01', deleted: 'false'});
db.country.insert({cid: 'Morocco' , name: 'Morocco', version: '01', deleted: 'false'});
db.country.insert({cid: 'Mozambique' , name: 'Mozambique', version: '01', deleted: 'false'});
db.country.insert({cid: 'Namibia' , name: 'Namibia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Nauru' , name: 'Nauru', version: '01', deleted: 'false'});
db.country.insert({cid: 'Nepal' , name: 'Nepal', version: '01', deleted: 'false'});
db.country.insert({cid: 'Kingdom of the Netherlands' , name: 'Kingdom of the Netherlands', version: '01', deleted: 'false'});
db.country.insert({cid: 'New Zealand' , name: 'New Zealand', version: '01', deleted: 'false'});
db.country.insert({cid: 'Nicaragua' , name: 'Nicaragua', version: '01', deleted: 'false'});
db.country.insert({cid: 'Niger' , name: 'Niger', version: '01', deleted: 'false'});
db.country.insert({cid: 'Nigeria' , name: 'Nigeria', version: '01', deleted: 'false'});
db.country.insert({cid: 'Norway' , name: 'Norway', version: '01', deleted: 'false'});
db.country.insert({cid: 'Oman' , name: 'Oman', version: '01', deleted: 'false'});
db.country.insert({cid: 'Pakistan' , name: 'Pakistan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Palau' , name: 'Palau', version: '01', deleted: 'false'});
db.country.insert({cid: 'State of Palestine' , name: 'State of Palestine', version: '01', deleted: 'false'});
db.country.insert({cid: 'Panama' , name: 'Panama', version: '01', deleted: 'false'});
db.country.insert({cid: 'Papua New Guinea' , name: 'Papua New Guinea', version: '01', deleted: 'false'});
db.country.insert({cid: 'Paraguay' , name: 'Paraguay', version: '01', deleted: 'false'});
db.country.insert({cid: 'Peru' , name: 'Peru', version: '01', deleted: 'false'});
db.country.insert({cid: 'Philippines' , name: 'Philippines', version: '01', deleted: 'false'});
db.country.insert({cid: 'Poland' , name: 'Poland', version: '01', deleted: 'false'});
db.country.insert({cid: 'Portugal' , name: 'Portugal', version: '01', deleted: 'false'});
db.country.insert({cid: 'Qatar' , name: 'Qatar', version: '01', deleted: 'false'});
db.country.insert({cid: 'Romania' , name: 'Romania', version: '01', deleted: 'false'});
db.country.insert({cid: 'Russia' , name: 'Russia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Rwanda' , name: 'Rwanda', version: '01', deleted: 'false'});
db.country.insert({cid: 'Saint Kitts and Nevis' , name: 'Saint Kitts and Nevis', version: '01', deleted: 'false'});
db.country.insert({cid: 'Saint Lucia' , name: 'Saint Lucia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Saint Vincent and the Grenadines' , name: 'Saint Vincent and the Grenadines', version: '01', deleted: 'false'});
db.country.insert({cid: 'Samoa' , name: 'Samoa', version: '01', deleted: 'false'});
db.country.insert({cid: 'San Marino' , name: 'San Marino', version: '01', deleted: 'false'});
db.country.insert({cid: 'Sao Tomé and Principe' , name: 'Sao Tomé and Principe', version: '01', deleted: 'false'});
db.country.insert({cid: 'Saudi Arabia' , name: 'Saudi Arabia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Senegal' , name: 'Senegal', version: '01', deleted: 'false'});
db.country.insert({cid: 'Serbia' , name: 'Serbia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Seychelles' , name: 'Seychelles', version: '01', deleted: 'false'});
db.country.insert({cid: 'Sierra Leone' , name: 'Sierra Leone', version: '01', deleted: 'false'});
db.country.insert({cid: 'Singapore' , name: 'Singapore', version: '01', deleted: 'false'});
db.country.insert({cid: 'Slovakia' , name: 'Slovakia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Slovenia' , name: 'Slovenia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Solomon Islands' , name: 'Solomon Islands', version: '01', deleted: 'false'});
db.country.insert({cid: 'Somalia' , name: 'Somalia', version: '01', deleted: 'false'});
db.country.insert({cid: 'South Africa' , name: 'South Africa', version: '01', deleted: 'false'});
db.country.insert({cid: 'South Sudan' , name: 'South Sudan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Spain' , name: 'Spain', version: '01', deleted: 'false'});
db.country.insert({cid: 'Sri Lanka' , name: 'Sri Lanka', version: '01', deleted: 'false'});
db.country.insert({cid: 'Sudan' , name: 'Sudan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Suriname' , name: 'Suriname', version: '01', deleted: 'false'});
db.country.insert({cid: 'Swaziland' , name: 'Swaziland', version: '01', deleted: 'false'});
db.country.insert({cid: 'Sweden' , name: 'Sweden', version: '01', deleted: 'false'});
db.country.insert({cid: 'Switzerland' , name: 'Switzerland', version: '01', deleted: 'false'});
db.country.insert({cid: 'Syria' , name: 'Syria', version: '01', deleted: 'false'});
db.country.insert({cid: 'Tajikistan' , name: 'Tajikistan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Tanzania' , name: 'Tanzania', version: '01', deleted: 'false'});
db.country.insert({cid: 'Thailand' , name: 'Thailand', version: '01', deleted: 'false'});
db.country.insert({cid: 'Togo' , name: 'Togo', version: '01', deleted: 'false'});
db.country.insert({cid: 'Tonga' , name: 'Tonga', version: '01', deleted: 'false'});
db.country.insert({cid: 'Trinidad and Tobago' , name: 'Trinidad and Tobago', version: '01', deleted: 'false'});
db.country.insert({cid: 'Tunisia' , name: 'Tunisia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Turkey' , name: 'Turkey', version: '01', deleted: 'false'});
db.country.insert({cid: 'Turkmenistan' , name: 'Turkmenistan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Tuvalu' , name: 'Tuvalu', version: '01', deleted: 'false'});
db.country.insert({cid: 'Uganda' , name: 'Uganda', version: '01', deleted: 'false'});
db.country.insert({cid: 'Ukraine' , name: 'Ukraine', version: '01', deleted: 'false'});
db.country.insert({cid: 'United Arab Emirates' , name: 'United Arab Emirates', version: '01', deleted: 'false'});
db.country.insert({cid: 'United Kingdom' , name: 'United Kingdom', version: '01', deleted: 'false'});
db.country.insert({cid: 'United States of America' , name: 'United States of America', version: '01', deleted: 'false'});
db.country.insert({cid: 'Uruguay' , name: 'Uruguay', version: '01', deleted: 'false'});
db.country.insert({cid: 'Uzbekistan' , name: 'Uzbekistan', version: '01', deleted: 'false'});
db.country.insert({cid: 'Vanuatu' , name: 'Vanuatu', version: '01', deleted: 'false'});
db.country.insert({cid: 'Vatican City' , name: 'Vatican City', version: '01', deleted: 'false'});
db.country.insert({cid: 'Venezuela' , name: 'Venezuela', version: '01', deleted: 'false'});
db.country.insert({cid: 'Vietnam' , name: 'Vietnam', version: '01', deleted: 'false'});
db.country.insert({cid: 'Yemen' , name: 'Yemen', version: '01', deleted: 'false'});
db.country.insert({cid: 'Zambia' , name: 'Zambia', version: '01', deleted: 'false'});
db.country.insert({cid: 'Zimbabwe' , name: 'Zimbabwe', version: '01', deleted: 'false'});
db.city.remove();
db.city.insert({cid: 'Afghanistan' , name: 'Kabul', version: '01', deleted: 'false'});
db.city.insert({cid: 'Albania' , name: 'Tirana', version: '01', deleted: 'false'});
db.city.insert({cid: 'Algeria' , name: 'Algiers', version: '01', deleted: 'false'});
db.city.insert({cid: 'Andorra' , name: 'Andorra la Vella', version: '01', deleted: 'false'});
db.city.insert({cid: 'Angola' , name: 'Luanda', version: '01', deleted: 'false'});
db.city.insert({cid: 'Antigua and Barbuda' , name: "St. John's", version: '01', deleted: 'false'});
db.city.insert({cid: 'Argentina' , name: 'Buenos Aires', version: '01', deleted: 'false'});
db.city.insert({cid: 'Armenia' , name: 'Yerevan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Canberra', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Sydney', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Melbourne', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Perth', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Adelaide', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Gold Coast', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Newcastle', version: '01', deleted: 'false'});
db.city.insert({cid: 'Australia' , name: 'Brisbane', version: '01', deleted: 'false'});
db.city.insert({cid: 'Austria' , name: 'Vienna', version: '01', deleted: 'false'});
db.city.insert({cid: 'Azerbaijan' , name: 'Baku', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bahamas' , name: 'Nassau', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bahrain' , name: 'Manama', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bangladesh' , name: 'Dhaka', version: '01', deleted: 'false'});
db.city.insert({cid: 'Barbados' , name: 'Bridgetown', version: '01', deleted: 'false'});
db.city.insert({cid: 'Belarus' , name: 'Minsk', version: '01', deleted: 'false'});
db.city.insert({cid: 'Belgium' , name: 'Brussels', version: '01', deleted: 'false'});
db.city.insert({cid: 'Belize' , name: 'Belmopan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Benin' , name: 'Porto-Novo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Benin' , name: 'Cotonou', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bhutan' , name: 'Thimphu', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bolivia' , name: 'Sucre', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bolivia' , name: 'La Paz', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bolivia' , name: 'Santa Cruz', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bosnia and Herzegovina' , name: 'Sarajevo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Botswana' , name: 'Gaborone', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'Brasília', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'São Paulo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'Rio de Janeiro', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'Salvador', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'Porto Alegre', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brazil' , name: 'Belo Horizonte', version: '01', deleted: 'false'});
db.city.insert({cid: 'Brunei' , name: 'Bandar Seri Begawan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Bulgaria' , name: 'Sofia', version: '01', deleted: 'false'});
db.city.insert({cid: 'Burkina Faso' , name: 'Ouagadougou', version: '01', deleted: 'false'});
db.city.insert({cid: 'Burma' , name: 'Naypyidaw (Pyinmana)', version: '01', deleted: 'false'});
db.city.insert({cid: 'Burma' , name: 'Yangon', version: '01', deleted: 'false'});
db.city.insert({cid: 'Burma' , name: 'Mandalay', version: '01', deleted: 'false'});
db.city.insert({cid: 'Burundi' , name: 'Bujumbura', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cambodia' , name: 'Phnom Penh', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cameroon' , name: 'Yaoundé', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cameroon' , name: 'Douala', version: '01', deleted: 'false'});
db.city.insert({cid: 'Canada' , name: 'Ottawa', version: '01', deleted: 'false'});
db.city.insert({cid: 'Canada' , name: 'Toronto', version: '01', deleted: 'false'});
db.city.insert({cid: 'Canada' , name: 'Montreal', version: '01', deleted: 'false'});
db.city.insert({cid: 'Canada' , name: 'Vancouver', version: '01', deleted: 'false'});
db.city.insert({cid: 'Canada' , name: 'Calgary', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cape Verde' , name: 'Praia', version: '01', deleted: 'false'});
db.city.insert({cid: 'Central African Republic' , name: 'Bangui', version: '01', deleted: 'false'});
db.city.insert({cid: 'Chad' , name: "N'Djamena", version: '01', deleted: 'false'});
db.city.insert({cid: 'Chile' , name: 'Santiago', version: '01', deleted: 'false'});
db.city.insert({cid: 'Chile' , name: 'Valparaíso', version: '01', deleted: 'false'});
db.city.insert({cid: 'China' , name: 'Beijing', version: '01', deleted: 'false'});
db.city.insert({cid: 'China' , name: 'Shanghai', version: '01', deleted: 'false'});
db.city.insert({cid: 'Colombia' , name: 'Bogotá', version: '01', deleted: 'false'});
db.city.insert({cid: 'Comoros' , name: 'Moroni', version: '01', deleted: 'false'});
db.city.insert({cid: 'Democratic Republic of the Congo' , name: 'Kinshasa', version: '01', deleted: 'false'});
db.city.insert({cid: 'Republic of the Congo' , name: 'Brazzaville', version: '01', deleted: 'false'});
db.city.insert({cid: 'Costa Rica' , name: 'San José', version: '01', deleted: 'false'});
db.city.insert({cid: 'Croatia' , name: 'Zagreb', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cuba' , name: 'Havana', version: '01', deleted: 'false'});
db.city.insert({cid: 'Cyprus' , name: 'Nicosia', version: '01', deleted: 'false'});
db.city.insert({cid: 'Czech Republic' , name: 'Prague', version: '01', deleted: 'false'});
db.city.insert({cid: 'Denmark' , name: 'Copenhagen', version: '01', deleted: 'false'});
db.city.insert({cid: 'Djibouti' , name: 'Djibouti', version: '01', deleted: 'false'});
db.city.insert({cid: 'Dominica' , name: 'Roseau', version: '01', deleted: 'false'});
db.city.insert({cid: 'Dominican Republic' , name: 'Santo Domingo', version: '01', deleted: 'false'});
db.city.insert({cid: 'East Timor' , name: 'Dili', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ecuador' , name: 'Quito', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ecuador' , name: 'Guayaquil', version: '01', deleted: 'false'});
db.city.insert({cid: 'Egypt' , name: 'Cairo', version: '01', deleted: 'false'});
db.city.insert({cid: 'El Salvador' , name: 'San Salvador', version: '01', deleted: 'false'});
db.city.insert({cid: 'Equatorial Guinea' , name: 'Malabo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Eritrea' , name: 'Asmara', version: '01', deleted: 'false'});
db.city.insert({cid: 'Estonia' , name: 'Tallinn', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ethiopia' , name: 'Addis Ababa', version: '01', deleted: 'false'});
db.city.insert({cid: 'Fiji' , name: 'Suva', version: '01', deleted: 'false'});
db.city.insert({cid: 'Finland' , name: 'Helsinki', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Paris', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Nantes', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Nice', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Lilles', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Poitier', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Toulouse', version: '01', deleted: 'false'});
db.city.insert({cid: 'France' , name: 'Rennes', version: '01', deleted: 'false'});
db.city.insert({cid: 'Gabon' , name: 'Libreville', version: '01', deleted: 'false'});
db.city.insert({cid: 'Gambia, The' , name: 'Banjul', version: '01', deleted: 'false'});
db.city.insert({cid: 'Georgia' , name: 'Tbilisi', version: '01', deleted: 'false'});
db.city.insert({cid: 'Germany' , name: 'Berlin', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ghana' , name: 'Accra', version: '01', deleted: 'false'});
db.city.insert({cid: 'Greece' , name: 'Athens', version: '01', deleted: 'false'});
db.city.insert({cid: 'Grenada' , name: "St. George's", version: '01', deleted: 'false'});
db.city.insert({cid: 'Guatemala' , name: 'Guatemala City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Guinea' , name: 'Conakry', version: '01', deleted: 'false'});
db.city.insert({cid: 'Guinea-Bissau' , name: 'Bissau', version: '01', deleted: 'false'});
db.city.insert({cid: 'Guyana' , name: 'Georgetown', version: '01', deleted: 'false'});
db.city.insert({cid: 'Haiti' , name: 'Port-au-Prince', version: '01', deleted: 'false'});
db.city.insert({cid: 'Honduras' , name: 'Tegucigalpa', version: '01', deleted: 'false'});
db.city.insert({cid: 'Hungary' , name: 'Budapest', version: '01', deleted: 'false'});
db.city.insert({cid: 'Iceland' , name: 'Reykjavík', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'New Delhi', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Delhi', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Mumbai', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Bangalore', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Hydrabad', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Ahmedabad', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Chennai', version: '01', deleted: 'false'});
db.city.insert({cid: 'India' , name: 'Kolkata', version: '01', deleted: 'false'});
db.city.insert({cid: 'Indonesia' , name: 'Jakarta', version: '01', deleted: 'false'});
db.city.insert({cid: 'Iran' , name: 'Tehran', version: '01', deleted: 'false'});
db.city.insert({cid: 'Iraq' , name: 'Baghdad', version: '01', deleted: 'false'});
db.city.insert({cid: 'Republic of Ireland' , name: 'Dublin', version: '01', deleted: 'false'});
db.city.insert({cid: 'Israel' , name: 'Jerusalem', version: '01', deleted: 'false'});
db.city.insert({cid: 'Israel' , name: 'Tel Aviv', version: '01', deleted: 'false'});
db.city.insert({cid: 'Italy' , name: 'Rome', version: '01', deleted: 'false'});
db.city.insert({cid: 'Italy' , name: 'Milan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Italy' , name: 'Naples', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ivory Coast' , name: 'Yamoussoukro', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ivory Coast' , name: 'Abidjan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Jamaica' , name: 'Kingston', version: '01', deleted: 'false'});
db.city.insert({cid: 'Japan' , name: 'Tokyo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Japan' , name: 'Kyoto', version: '01', deleted: 'false'});
db.city.insert({cid: 'Jordan' , name: 'Amman', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kazakhstan' , name: 'Astana', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kazakhstan' , name: 'Almaty', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kazakhstan' , name: 'Shymkent', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kenya' , name: 'Nairobi', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kiribati' , name: 'South Tarawa', version: '01', deleted: 'false'});
db.city.insert({cid: 'North Korea' , name: 'Pyongyang', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Korea' , name: 'Seoul', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kuwait' , name: 'Kuwait City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kyrgyzstan' , name: 'Bishkek', version: '01', deleted: 'false'});
db.city.insert({cid: 'Laos' , name: 'Vientiane', version: '01', deleted: 'false'});
db.city.insert({cid: 'Latvia' , name: 'Riga', version: '01', deleted: 'false'});
db.city.insert({cid: 'Lebanon' , name: 'Beirut', version: '01', deleted: 'false'});
db.city.insert({cid: 'Lesotho' , name: 'Maseru', version: '01', deleted: 'false'});
db.city.insert({cid: 'Liberia' , name: 'Monrovia', version: '01', deleted: 'false'});
db.city.insert({cid: 'Libya' , name: 'Tripoli', version: '01', deleted: 'false'});
db.city.insert({cid: 'Liechtenstein' , name: 'Vaduz', version: '01', deleted: 'false'});
db.city.insert({cid: 'Liechtenstein' , name: 'Schaan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Lithuania' , name: 'Vilnius', version: '01', deleted: 'false'});
db.city.insert({cid: 'Luxembourg' , name: 'Luxembourg City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Republic of Macedonia' , name: 'Skopje', version: '01', deleted: 'false'});
db.city.insert({cid: 'Madagascar' , name: 'Antananarivo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Malawi' , name: 'Lilongwe', version: '01', deleted: 'false'});
db.city.insert({cid: 'Malaysia' , name: 'Kuala Lumpur', version: '01', deleted: 'false'});
db.city.insert({cid: 'Malaysia' , name: 'Putrajaya', version: '01', deleted: 'false'});
db.city.insert({cid: 'Maldives' , name: 'Malé', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mali' , name: 'Bamako', version: '01', deleted: 'false'});
db.city.insert({cid: 'Malta' , name: 'Valletta', version: '01', deleted: 'false'});
db.city.insert({cid: 'Marshall Islands' , name: 'Majuro', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mauritania' , name: 'Nouakchott', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mauritius' , name: 'Port Louis', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mexico' , name: 'Mexico City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Federated States of Micronesia' , name: 'Palikir', version: '01', deleted: 'false'});
db.city.insert({cid: 'Federated States of Micronesia' , name: 'Weno', version: '01', deleted: 'false'});
db.city.insert({cid: 'Moldova' , name: 'Chisinau', version: '01', deleted: 'false'});
db.city.insert({cid: 'Monaco' , name: 'Monaco', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mongolia' , name: 'Ulan Bator', version: '01', deleted: 'false'});
db.city.insert({cid: 'Montenegro' , name: 'Podgorica', version: '01', deleted: 'false'});
db.city.insert({cid: 'Morocco' , name: 'Rabat', version: '01', deleted: 'false'});
db.city.insert({cid: 'Morocco' , name: 'Casablanca', version: '01', deleted: 'false'});
db.city.insert({cid: 'Mozambique' , name: 'Maputo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Namibia' , name: 'Windhoek', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nauru' , name: 'inYaren', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nauru' , name: 'Denigomodu', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nauru' , name: 'Meneng', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nauru' , name: 'Aiwo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nepal' , name: 'Kathmandu', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kingdom of the Netherlands' , name: 'The Hague', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kingdom of the Netherlands' , name: 'Rotterdam', version: '01', deleted: 'false'});
db.city.insert({cid: 'Kingdom of the Netherlands' , name: 'Amsterdam', version: '01', deleted: 'false'});
db.city.insert({cid: 'New Zealand' , name: 'Wellington', version: '01', deleted: 'false'});
db.city.insert({cid: 'New Zealand' , name: 'Auckland', version: '01', deleted: 'false'});
db.city.insert({cid: 'New Zealand' , name: 'Christchurch', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nicaragua' , name: 'Managua', version: '01', deleted: 'false'});
db.city.insert({cid: 'Niger' , name: 'Niamey', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Abuja', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Lagos', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Ibadan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Kano', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Ilorin', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Port Harcourt', version: '01', deleted: 'false'});
db.city.insert({cid: 'Nigeria' , name: 'Ogbomosho', version: '01', deleted: 'false'});
db.city.insert({cid: 'Norway' , name: 'Oslo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Oman' , name: 'Muscat', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Islamabad', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Lahore', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Faisalabad', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Rawalpindi', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Gujranwala', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Multan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Hyderabad', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Peshawar', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Quetta', version: '01', deleted: 'false'});
db.city.insert({cid: 'Pakistan' , name: 'Karachi', version: '01', deleted: 'false'});
db.city.insert({cid: 'Palau' , name: 'Ngerulmud', version: '01', deleted: 'false'});
db.city.insert({cid: 'Palau' , name: 'Koror', version: '01', deleted: 'false'});
db.city.insert({cid: 'Palau' , name: 'Meyuns', version: '01', deleted: 'false'});
db.city.insert({cid: 'Palau' , name: 'Airai', version: '01', deleted: 'false'});
db.city.insert({cid: 'State of Palestine' , name: 'Jerusalem', version: '01', deleted: 'false'});
db.city.insert({cid: 'State of Palestine' , name: 'Gaza', version: '01', deleted: 'false'});
db.city.insert({cid: 'State of Palestine' , name: 'Ramallah', version: '01', deleted: 'false'});
db.city.insert({cid: 'State of Palestine' , name: 'West Bank', version: '01', deleted: 'false'});
db.city.insert({cid: 'Panama' , name: 'Panama City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Papua New Guinea' , name: 'Port Moresby', version: '01', deleted: 'false'});
db.city.insert({cid: 'Paraguay' , name: 'Asunción', version: '01', deleted: 'false'});
db.city.insert({cid: 'Peru' , name: 'Lima', version: '01', deleted: 'false'});
db.city.insert({cid: 'Philippines' , name: 'Manila', version: '01', deleted: 'false'});
db.city.insert({cid: 'Philippines' , name: 'Quezon City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Poland' , name: 'Warsaw', version: '01', deleted: 'false'});
db.city.insert({cid: 'Portugal' , name: 'Lisbon', version: '01', deleted: 'false'});
db.city.insert({cid: 'Qatar' , name: 'Doha', version: '01', deleted: 'false'});
db.city.insert({cid: 'Romania' , name: 'Bucharest', version: '01', deleted: 'false'});
db.city.insert({cid: 'Russia' , name: 'Moscow', version: '01', deleted: 'false'});
db.city.insert({cid: 'Rwanda' , name: 'Kigali', version: '01', deleted: 'false'});
db.city.insert({cid: 'Saint Kitts and Nevis' , name: 'Basseterre', version: '01', deleted: 'false'});
db.city.insert({cid: 'Saint Lucia' , name: 'Castries', version: '01', deleted: 'false'});
db.city.insert({cid: 'Saint Vincent and the Grenadines' , name: 'Kingstown', version: '01', deleted: 'false'});
db.city.insert({cid: 'Samoa' , name: 'Apia', version: '01', deleted: 'false'});
db.city.insert({cid: 'San Marino' , name: 'San Marino', version: '01', deleted: 'false'});
db.city.insert({cid: 'San Marino' , name: 'Serravalle', version: '01', deleted: 'false'});
db.city.insert({cid: 'San Marino' , name: 'Borgo Maggiore', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sao Tomé and Principe' , name: 'Sao Tomé', version: '01', deleted: 'false'});
db.city.insert({cid: 'Saudi Arabia' , name: 'Riyadh', version: '01', deleted: 'false'});
db.city.insert({cid: 'Senegal' , name: 'Dakar', version: '01', deleted: 'false'});
db.city.insert({cid: 'Serbia' , name: 'Belgrade', version: '01', deleted: 'false'});
db.city.insert({cid: 'Seychelles' , name: 'Victoria', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sierra Leone' , name: 'Freetown', version: '01', deleted: 'false'});
db.city.insert({cid: 'Singapore' , name: 'Singapore', version: '01', deleted: 'false'});
db.city.insert({cid: 'Slovakia' , name: 'Bratislava', version: '01', deleted: 'false'});
db.city.insert({cid: 'Slovenia' , name: 'Ljubljana', version: '01', deleted: 'false'});
db.city.insert({cid: 'Solomon Islands' , name: 'Honiara', version: '01', deleted: 'false'});
db.city.insert({cid: 'Somalia' , name: 'Mogadishu', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Africa' , name: 'Pretoria', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Africa' , name: 'Cape Town', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Africa' , name: 'Bloemfontein', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Africa' , name: 'Durban', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Africa' , name: 'Johannesburg', version: '01', deleted: 'false'});
db.city.insert({cid: 'South Sudan' , name: 'Juba', version: '01', deleted: 'false'});
db.city.insert({cid: 'Spain' , name: 'Madrid', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sri Lanka' , name: 'Sri Jayawardenapura Kotte', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sri Lanka' , name: 'Colombo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sudan' , name: 'Omdurman', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sudan' , name: 'Khartoum', version: '01', deleted: 'false'});
db.city.insert({cid: 'Suriname' , name: 'Paramaribo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Swaziland' , name: 'Mbabane', version: '01', deleted: 'false'});
db.city.insert({cid: 'Swaziland' , name: 'Lobamba', version: '01', deleted: 'false'});
db.city.insert({cid: 'Swaziland' , name: 'Manzini', version: '01', deleted: 'false'});
db.city.insert({cid: 'Sweden' , name: 'Stockholm', version: '01', deleted: 'false'});
db.city.insert({cid: 'Switzerland' , name: 'Bern', version: '01', deleted: 'false'});
db.city.insert({cid: 'Switzerland' , name: 'Zurich', version: '01', deleted: 'false'});
db.city.insert({cid: 'Switzerland' , name: 'Geneva', version: '01', deleted: 'false'});
db.city.insert({cid: 'Switzerland' , name: 'Basel', version: '01', deleted: 'false'});
db.city.insert({cid: 'Switzerland' , name: 'Lausanne', version: '01', deleted: 'false'});
db.city.insert({cid: 'Syria' , name: 'Damascus', version: '01', deleted: 'false'});
db.city.insert({cid: 'Syria' , name: 'Aleppo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tajikistan' , name: 'Dushanbe', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tanzania' , name: 'Dodoma', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tanzania' , name: 'Dar es Salaam', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tanzania' , name: 'Mwanza', version: '01', deleted: 'false'});
db.city.insert({cid: 'Thailand' , name: 'Bangkok', version: '01', deleted: 'false'});
db.city.insert({cid: 'Togo' , name: 'Lomé', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tonga' , name: "Nuku'alofa", version: '01', deleted: 'false'});
db.city.insert({cid: 'Trinidad and Tobago' , name: 'Port of Spain', version: '01', deleted: 'false'});
db.city.insert({cid: 'Trinidad and Tobago' , name: 'Chaguanas', version: '01', deleted: 'false'});
db.city.insert({cid: 'Trinidad and Tobago' , name: 'San Fernando', version: '01', deleted: 'false'});
db.city.insert({cid: 'Trinidad and Tobago' , name: 'San Juan', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tunisia' , name: 'Tunis', version: '01', deleted: 'false'});
db.city.insert({cid: 'Turkey' , name: 'Ankara', version: '01', deleted: 'false'});
db.city.insert({cid: 'Turkey' , name: 'Istanbul', version: '01', deleted: 'false'});
db.city.insert({cid: 'Turkmenistan' , name: 'Ashgabat', version: '01', deleted: 'false'});
db.city.insert({cid: 'Tuvalu' , name: 'Funafuti', version: '01', deleted: 'false'});
db.city.insert({cid: 'Uganda' , name: 'Kampala', version: '01', deleted: 'false'});
db.city.insert({cid: 'Ukraine' , name: 'Kiev', version: '01', deleted: 'false'});
db.city.insert({cid: 'United Arab Emirates' , name: 'Abu Dhabi', version: '01', deleted: 'false'});
db.city.insert({cid: 'United Arab Emirates' , name: 'Dubai', version: '01', deleted: 'false'});
db.city.insert({cid: 'United Arab Emirates' , name: 'Sharjah', version: '01', deleted: 'false'});
db.city.insert({cid: 'United Kingdom' , name: 'London', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Washington, D.C.', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'New York City', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Los Angeles', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Chicago', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Houston', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Philadelphia', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Phoenix', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'San Antonio', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'San Diego', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Dallas', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'San Jose', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Austin', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Jacksonville', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Indianapolis', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'San Francisco', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Columbus', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Fort Worth', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Charlotte', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Detroit', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'El Paso', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Memphis', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Boston', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Seattle', version: '01', deleted: 'false'});
db.city.insert({cid: 'United States of America' , name: 'Denver', version: '01', deleted: 'false'});
db.city.insert({cid: 'Uruguay' , name: 'Montevideo', version: '01', deleted: 'false'});
db.city.insert({cid: 'Uzbekistan' , name: 'Tashkent', version: '01', deleted: 'false'});
db.city.insert({cid: 'Vanuatu' , name: 'Port Vila', version: '01', deleted: 'false'});
db.city.insert({cid: 'Vatican City' , name: 'Vatican City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Venezuela' , name: 'Caracas', version: '01', deleted: 'false'});
db.city.insert({cid: 'Vietnam' , name: 'Hanoi', version: '01', deleted: 'false'});
db.city.insert({cid: 'Vietnam' , name: 'Ho Chi Minh City', version: '01', deleted: 'false'});
db.city.insert({cid: 'Yemen' , name: "Sana'a", version: '01', deleted: 'false'});
db.city.insert({cid: 'Zambia' , name: 'Lusaka', version: '01', deleted: 'false'});
db.city.insert({cid: 'Zimbabwe' , name: 'Harare', version: '01', deleted: 'false'});